/**
 * deriveParity.mjs — proves lib/derive.js (the JS port) matches the backend
 * app/derive.py bit-for-bit on every NUMERIC assumption field (`_drivers`
 * provenance strings are exempt). Cases are generated by the Python backend:
 *
 *   python tests/gen_derive_cases.py <frontend>/tests/deriveCases.json
 *   node tests/deriveParity.mjs
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { deriveAssumptions } from "../src/lib/derive.js";

const here = dirname(fileURLToPath(import.meta.url));
const cases = JSON.parse(readFileSync(join(here, "deriveCases.json"), "utf8"));

const close = (a, b) => {
  if (a == null && b == null) return true;
  if (a == null || b == null) return false;
  if (typeof b === "string") return a === b;
  const denom = Math.max(1e-9, Math.abs(b));
  return Math.abs(a - b) / denom < 1e-9;
};

let pass = 0, fail = 0;
for (let i = 0; i < cases.length; i++) {
  const c = cases[i];
  const got = deriveAssumptions(c.statements, c.vs, c.is_financial);
  const bad = [];
  for (const [k, expV] of Object.entries(c.exp)) {
    if (!close(got[k], expV)) bad.push(`${k}: js=${got[k]} py=${expV}`);
  }
  if (!bad.length) {
    pass++;
  } else {
    fail++;
    console.log(`  ✗ case ${i} [${c.vs} ${c.is_financial ? "financial" : "nonfin"} ` +
                `${Object.keys(c.statements).length}y]`);
    for (const b of bad) console.log(`      ${b}`);
  }
}
console.log(`\n${pass}/${cases.length} derive cases match the backend (tol 1e-9 relative).`);
process.exit(fail === 0 ? 0 : 1);
