/**
 * engineParity.mjs — proves lib/engine.js (the JS port) matches the backend
 * app/engines.py bit-for-bit. Cases are generated by the Python backend into
 * /tmp/parity_cases.json (see the generator in the audit), then recomputed here
 * and compared. Any divergence beyond floating-point noise fails.
 *
 * Run:  node tests/engineParity.mjs
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { blended } from "../src/lib/engine.js";

// Snapshot of backend (app/engines.py) outputs over 60 random cases. Regenerate
// with the Python generator in the audit when engines.py changes.
const here = dirname(fileURLToPath(import.meta.url));
const cases = JSON.parse(readFileSync(join(here, "parityCases.json"), "utf8"));

const close = (a, b) => {
  if (a == null && b == null) return true;
  if (a == null || b == null) return false;
  const denom = Math.max(1e-9, Math.abs(b));
  return Math.abs(a - b) / denom < 1e-9;
};

let pass = 0, fail = 0;
for (let i = 0; i < cases.length; i++) {
  const c = cases[i];
  const r = blended(c.co, c.a);
  const okB = close(r.blended, c.exp_blended);
  const okP = close(r.primary, c.exp_primary);
  const okC = (r.components || []).every((comp, j) => close(comp.value, c.exp_components[j]));
  if (okB && okP && okC) {
    pass++;
  } else {
    fail++;
    console.log(`  ✗ case ${i} [${c.a._valuation_sector} ${c.co.type}]`);
    if (!okB) console.log(`      blended:   js=${r.blended}  py=${c.exp_blended}`);
    if (!okP) console.log(`      primary:   js=${r.primary}  py=${c.exp_primary}`);
    if (!okC) console.log(`      components js=${JSON.stringify((r.components||[]).map(x=>x.value))} py=${JSON.stringify(c.exp_components)}`);
  }
}
console.log(`\n${pass}/${cases.length} cases match the backend (tol 1e-9 relative).`);
process.exit(fail === 0 ? 0 : 1);
