/**
 * verdictParity.mjs — proves lib/recommend.js emits the SAME VERDICT STRING as
 * the backend's app/engines.recommend for the same company + assumptions.
 *
 * engineParity pins the intrinsic and deriveParity pins the assumptions; this
 * pins the label the user actually reads. It matters because recommend.js is
 * not decorative: valuationView() runs it for every seed / offline row (the
 * whole screener whenever /api/companies fails) and Company.jsx runs it for the
 * header and Verdict tab while /api/companies/{ticker} loads. A ladder that
 * disagrees with the server puts a different word on the same name depending on
 * which path rendered it — the "TRIM" vs "REDUCE" drift was exactly that.
 *
 * Cases are generated by the Python backend (every zone edge and gate, see the
 * generator's docstring):
 *
 *   python tests/gen_verdict_cases.py <frontend>/tests/verdictCases.json
 *   node tests/verdictParity.mjs
 *
 * The comparison is an EXACT string match on the verdict. mos / composite /
 * confidence are printed on a mismatch as diagnostics only, so a failure can be
 * attributed (band edge vs composite leg vs confidence gate) without re-running
 * Python. Assumes engineParity and deriveParity are green — a drift there shows
 * up here too, and those harnesses name it first.
 */
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { recommend } from "../src/lib/recommend.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = join(here, "verdictCases.json");
if (!existsSync(fixture)) {
  console.error("verdictParity: tests/verdictCases.json is missing — generate it from the " +
                "backend: python tests/gen_verdict_cases.py <frontend>/tests/verdictCases.json " +
                "(or bash scripts/sync_parity_fixtures.sh), then commit it.");
  process.exit(1);
}
const cases = JSON.parse(readFileSync(fixture, "utf8"));

/* The fixture carries the company in the backend's snake_case shape (what
   assemble.build_company emits and /api/companies serialises). This is the same
   field-name translation seedData.buildFromApi() + Company.jsx's `co2` perform
   before handing a row to recommend(); nothing is added or defaulted here. */
const toClientCo = (co) => ({
  id: co.ticker, ticker: co.ticker, name: co.name,
  type: co.type, sector: co.sector,
  template_code: co.template_code, valuation_sector: co.valuation_sector,
  price: co.price ?? null, shares: co.shares ?? null, equity: co.equity ?? null,
  netProfit: co.net_profit ?? null, revenue: co.revenue ?? null, netDebt: co.net_debt ?? null,
  nbfc: co.nbfc ?? undefined,
  series: co.series ?? [], syntheticSeries: Boolean(co.synthetic_series),
  statements: co.statements ?? {},
  dataWarning: co.data_warning ?? undefined,
});

const fmt = (x) => (x == null ? "null" : typeof x === "number" ? x.toFixed(4) : String(x));

let pass = 0, fail = 0;
const shapes = {};
for (let i = 0; i < cases.length; i++) {
  const c = cases[i];
  let got;
  try {
    got = recommend(toClientCo(c.co), c.a);
  } catch (e) {
    got = { verdict: `THREW ${e.message}` };
  }
  if (got.verdict === c.exp_verdict) {
    pass++;
  } else {
    fail++;
    const k = `${c.exp_verdict} -> ${got.verdict}`;
    shapes[k] = (shapes[k] || 0) + 1;
    console.log(`  ✗ case ${i} [${c.label}]`);
    console.log(`      verdict:    js=${got.verdict}  py=${c.exp_verdict}` +
                (c.exp_gate && c.exp_gate !== "clean" ? `  (py gate ${c.exp_gate})` : ""));
    console.log(`      mos:        js=${fmt(got.mos)}  py=${fmt(c.exp_mos)}`);
    console.log(`      composite:  js=${fmt(got.composite)}  py=${fmt(c.exp_composite)}`);
    console.log(`      confidence: js=${got.confidence?.level}  py=${c.exp_conf_level}`);
  }
}
if (fail) {
  console.log("\n  mismatch shapes (py -> js):");
  for (const [k, n] of Object.entries(shapes).sort((a, b) => b[1] - a[1]))
    console.log(`    ${String(n).padStart(3)}  ${k}`);
}
console.log(`\n${pass}/${cases.length} verdict cases match the backend (exact string).`);
process.exit(fail === 0 ? 0 : 1);
